### ISSUE TITLE
Allow overriding the leapp-tool path used from the cockpit UI

### ISSUE THREAD

**Issue by vinzenz** [leapp-to/prototype#114]
In integration tests and development environments we should allow to override the path of the leapp-tool to be used in the cockpit UI

Right now the location is /usr/bin/leapp-tool

**Comment by ncoghlan** [comment]
Since it's just for the integration tests & for running the demo from the checkout, one option would be to do an existence check in the plugin and use /opt/leapp/bin/leapp-tool if it exists, and otherwise use /usr/bin/leapp-tool

After making my comment on #102, I realised that making it generally configurable is asking for trouble, since the plugin currently runs it with escalated privileges.

**Comment by ncoghlan** [comment]
https://github.com/leapp-to/prototype/pull/116 adjusted the current behaviour such that a git clone will use `/opt/leapp/bin/leapp-tool` by default, while an installed version will use `/usr/bin/leapp-tool`.

A more robust solution would be to introduce a proper configuration file for the plugin, so user level settings can't alter the behaviour of a system-installed plugin, but we also won't need to edit the HTML with sed while generating the RPMs.

**Comment by ncoghlan** [comment]
https://github.com/leapp-to/prototype/pull/117 added config file support, so is there anything left to be done here?

**Comment by vinzenz** [comment]
No this has been forgotten to be closed
